
glasgow_traders:

  target: dev

  outputs:

    dev:

      type: snowflake

      account: mfpdbyb-ah29077

      user: LARIOUS

      password: dDiHcDqv3WrC3iR

      role: ACCOUNTADMIN

      warehouse: AUTOPIPE_WH

      database: GLASGOW_TRADERS

      schema: INTERMEDIATE

      threads: 1

